### ISSUE TITLE
RuntimeError: Expected hasRecord("version") to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

### ISSUE THREAD

**Issue by YuzhenD** [Nithin-GK/AT-DDPM#1]
Hey, bro! I have an issue of the inference code.
When running the code: 
CUDA_VISIBLE_DEVICES="0" NCCL_P2P_DISABLE=1  torchrun --nproc_per_node=1 --master_port=4326 /content/AT-DDPM/scripts/AT_test.py
It throws the following RuntimeError:
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 3
wandb: You chose "Don't visualize my results"
wandb: Tracking run with wandb version 0.13.10
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
Logging to ./experiments/log/
creating model...
Traceback (most recent call last):
  File "/content/AT-DDPM/scripts/AT_test.py", line 64, in <module>
    main(run)
  File "/content/AT-DDPM/scripts/AT_test.py", line 43, in main
    dist_util.load_state_dict(model_weights, map_location="cpu")
  File "/content/AT-DDPM/scripts/guided_diffusion/dist_util.py", line 64, in load_state_dict
    return th.load(path, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 777, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: Expected hasRecord("version") to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
wandb: Waiting for W&B process to finish... (failed 1).
wandb: You can sync this run to the cloud by running:
wandb: wandb sync ./experiments/wandb/offline-run-20230211_073935-4lemxvfb
wandb: Find logs at: ./experiments/wandb/offline-run-20230211_073935-4lemxvfb/logs

**Comment by Nithin-GK** [comment]
Fixed

**Comment by jinshuhua** [comment]
> Fixed

can you tell me how to fix it?

**Comment by YuhaoW182** [comment]
I can't express how grateful I am if you could tell me how to solve it.
